// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: warmup.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WarmupServiceClient is the client API for WarmupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarmupServiceClient interface {
	Unary(ctx context.Context, in *WarmupRequest, opts ...grpc.CallOption) (*WarmupResponse, error)
	ServerStreaming(ctx context.Context, in *WarmupRequest, opts ...grpc.CallOption) (WarmupService_ServerStreamingClient, error)
	ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (WarmupService_ClientStreamingClient, error)
	BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (WarmupService_BidiStreamingClient, error)
	Empty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type warmupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarmupServiceClient(cc grpc.ClientConnInterface) WarmupServiceClient {
	return &warmupServiceClient{cc}
}

func (c *warmupServiceClient) Unary(ctx context.Context, in *WarmupRequest, opts ...grpc.CallOption) (*WarmupResponse, error) {
	out := new(WarmupResponse)
	err := c.cc.Invoke(ctx, "/warmup.WarmupService/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warmupServiceClient) ServerStreaming(ctx context.Context, in *WarmupRequest, opts ...grpc.CallOption) (WarmupService_ServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &WarmupService_ServiceDesc.Streams[0], "/warmup.WarmupService/ServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &warmupServiceServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WarmupService_ServerStreamingClient interface {
	Recv() (*WarmupResponse, error)
	grpc.ClientStream
}

type warmupServiceServerStreamingClient struct {
	grpc.ClientStream
}

func (x *warmupServiceServerStreamingClient) Recv() (*WarmupResponse, error) {
	m := new(WarmupResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *warmupServiceClient) ClientStreaming(ctx context.Context, opts ...grpc.CallOption) (WarmupService_ClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &WarmupService_ServiceDesc.Streams[1], "/warmup.WarmupService/ClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &warmupServiceClientStreamingClient{stream}
	return x, nil
}

type WarmupService_ClientStreamingClient interface {
	Send(*WarmupRequest) error
	CloseAndRecv() (*WarmupResponse, error)
	grpc.ClientStream
}

type warmupServiceClientStreamingClient struct {
	grpc.ClientStream
}

func (x *warmupServiceClientStreamingClient) Send(m *WarmupRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *warmupServiceClientStreamingClient) CloseAndRecv() (*WarmupResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WarmupResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *warmupServiceClient) BidiStreaming(ctx context.Context, opts ...grpc.CallOption) (WarmupService_BidiStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &WarmupService_ServiceDesc.Streams[2], "/warmup.WarmupService/BidiStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &warmupServiceBidiStreamingClient{stream}
	return x, nil
}

type WarmupService_BidiStreamingClient interface {
	Send(*WarmupRequest) error
	Recv() (*WarmupResponse, error)
	grpc.ClientStream
}

type warmupServiceBidiStreamingClient struct {
	grpc.ClientStream
}

func (x *warmupServiceBidiStreamingClient) Send(m *WarmupRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *warmupServiceBidiStreamingClient) Recv() (*WarmupResponse, error) {
	m := new(WarmupResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *warmupServiceClient) Empty(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/warmup.WarmupService/Empty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarmupServiceServer is the server API for WarmupService service.
// All implementations must embed UnimplementedWarmupServiceServer
// for forward compatibility
type WarmupServiceServer interface {
	Unary(context.Context, *WarmupRequest) (*WarmupResponse, error)
	ServerStreaming(*WarmupRequest, WarmupService_ServerStreamingServer) error
	ClientStreaming(WarmupService_ClientStreamingServer) error
	BidiStreaming(WarmupService_BidiStreamingServer) error
	Empty(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedWarmupServiceServer()
}

// UnimplementedWarmupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWarmupServiceServer struct {
}

func (UnimplementedWarmupServiceServer) Unary(context.Context, *WarmupRequest) (*WarmupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedWarmupServiceServer) ServerStreaming(*WarmupRequest, WarmupService_ServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreaming not implemented")
}
func (UnimplementedWarmupServiceServer) ClientStreaming(WarmupService_ClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStreaming not implemented")
}
func (UnimplementedWarmupServiceServer) BidiStreaming(WarmupService_BidiStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStreaming not implemented")
}
func (UnimplementedWarmupServiceServer) Empty(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Empty not implemented")
}
func (UnimplementedWarmupServiceServer) mustEmbedUnimplementedWarmupServiceServer() {}

// UnsafeWarmupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarmupServiceServer will
// result in compilation errors.
type UnsafeWarmupServiceServer interface {
	mustEmbedUnimplementedWarmupServiceServer()
}

func RegisterWarmupServiceServer(s grpc.ServiceRegistrar, srv WarmupServiceServer) {
	s.RegisterService(&WarmupService_ServiceDesc, srv)
}

func _WarmupService_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmupServiceServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warmup.WarmupService/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmupServiceServer).Unary(ctx, req.(*WarmupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarmupService_ServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WarmupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarmupServiceServer).ServerStreaming(m, &warmupServiceServerStreamingServer{stream})
}

type WarmupService_ServerStreamingServer interface {
	Send(*WarmupResponse) error
	grpc.ServerStream
}

type warmupServiceServerStreamingServer struct {
	grpc.ServerStream
}

func (x *warmupServiceServerStreamingServer) Send(m *WarmupResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WarmupService_ClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WarmupServiceServer).ClientStreaming(&warmupServiceClientStreamingServer{stream})
}

type WarmupService_ClientStreamingServer interface {
	SendAndClose(*WarmupResponse) error
	Recv() (*WarmupRequest, error)
	grpc.ServerStream
}

type warmupServiceClientStreamingServer struct {
	grpc.ServerStream
}

func (x *warmupServiceClientStreamingServer) SendAndClose(m *WarmupResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *warmupServiceClientStreamingServer) Recv() (*WarmupRequest, error) {
	m := new(WarmupRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WarmupService_BidiStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WarmupServiceServer).BidiStreaming(&warmupServiceBidiStreamingServer{stream})
}

type WarmupService_BidiStreamingServer interface {
	Send(*WarmupResponse) error
	Recv() (*WarmupRequest, error)
	grpc.ServerStream
}

type warmupServiceBidiStreamingServer struct {
	grpc.ServerStream
}

func (x *warmupServiceBidiStreamingServer) Send(m *WarmupResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *warmupServiceBidiStreamingServer) Recv() (*WarmupRequest, error) {
	m := new(WarmupRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WarmupService_Empty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarmupServiceServer).Empty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/warmup.WarmupService/Empty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarmupServiceServer).Empty(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WarmupService_ServiceDesc is the grpc.ServiceDesc for WarmupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarmupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warmup.WarmupService",
	HandlerType: (*WarmupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _WarmupService_Unary_Handler,
		},
		{
			MethodName: "Empty",
			Handler:    _WarmupService_Empty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStreaming",
			Handler:       _WarmupService_ServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreaming",
			Handler:       _WarmupService_ClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidiStreaming",
			Handler:       _WarmupService_BidiStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "warmup.proto",
}
